# SITE CONFIGURATION
baseurl: ""
url: "https://assada.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Assada`s Blog
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: 17a524bd0be05c1b2ca7cb59d95a2d57
  description: "Software Developer Alex Ilyenko" # used by search engines

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text:

  # Icons
  rss: true
  email_address: assada.ua@gmail.com
  behance:
  bitbucket: Assada
  dribbble:
  facebook: 100006772187574
  flickr:
  gitlab: Assada
  github: "Assada"
  google_plus:
  instagram: assada_ua
  linkedin:  https://www.linkedin.com/in/assada/
  pinterest:
  reddit:
  soundcloud: assada_ua
  stack_exchange:  # Full URL
  steam: AssadaUa
  tumblr:
  twitter: "assada_ua"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-97323069-1
  disqus_shortname: assada-github-io
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
