# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://assada.github.io/" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Assada`s Blog
  avatar: avatar.png
  gravatar: 17a524bd0be05c1b2ca7cb59d95a2d57
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text:

  # Icons
  rss: false
  email_address: assada.ua@gmail.com
  behance:
  bitbucket: Assada
  dribbble:
  facebook: 100006772187574
  flickr:
  github: "Assada"
  google_plus:
  instagram: assada_ua
  linkedin: https://www.linkedin.com/in/a-alekseev/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam: AssadaUa
  tumblr:
  twitter: "assada_ua"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
